### ISSUE TITLE
Character entity reference

### ISSUE THREAD

**Issue by jim-rosales** [kentrepreneur/prj-rev-bwfs-dasmoto#4]
When using special symbols like the ampersand symbol it is best practice to include them in a page by using their [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). This [reference](https://dev.w3.org/html5/html-author/charref) sheet has the most common symbols and the reference used to include them in HTML files. 

Here you'd replace `&` with `&amp;` once you make this change GitHub will remove the red background shown below. 

https://github.com/kentrepreneur/prj-rev-bwfs-dasmoto/blob/57f8a4fff5e5c94dcfd592d5349bc1450b9eb43e/Dasmoto%20Arts/index.html#L12

**Comment by kentrepreneur** [comment]
I think I need to learn more about github.  I can't figure out how to make edits as you suggested.

**Comment by jim-rosales** [comment]
That's fine; it takes a while to get used to GitHub. Just keep this suggestion in mind as you work on future projects! You can also just make the change to this project on the local copy that you have on your machine.
